### ISSUE TITLE
Saying it sends but does not (for Yolo)

### ISSUE THREAD

**Issue by Wischin** [samplics/anonymous-snapchat-spammer#1]
The program worked perfectly a few days ago, but now it just doesn't send the actual messages. It may be that Yolo has changed up its system, but other than that it doesn't work anymore.

To be more specific, the program when run, says it is sending the messages successfully to the target, but when I tested the program on myself, there were no messages popping up in my Yolo inbox :/ 

(the program stopped working yesterday)

Please fix this, lol, I loved trolling people with it.

**Comment by samplics** [comment]
> The program worked perfectly a few days ago, but now it just doesn't send the actual messages. It may be that Yolo has changed up its system, but other than that it doesn't work anymore.
> 
> 
> 
> 
> 
> To be more specific, the program when run, says it is sending the messages successfully to the target, but when I tested the program on myself, there were no messages popping up in my Yolo inbox :/ 
> 
> 
> 
> (the program stopped working yesterday)
> 
> 
> 
> Please fix this, lol, I loved trolling people with it. 

I'll look into it, thanks!
